/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "includes.h"
#include "DIALOG.h"
#include "./Bsp/ov2640/bsp_ov2640.h"
// USER END

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
OV2640_IDTypeDef OV2640_Camera_ID;
// USER END
extern uint8_t shot_flag;
extern KEY Key1;
extern OS_SEM   SEM_SHOT;
/*********************************************************************
*
*       CreateCamera
*/
void Camera(void)
{ 
  OS_ERR err;
  /* Initializes the DCMI interface (I2C and GPIO) used to configure the camera */
  OV2640_HW_Init();  
  
  /* Read the OV9655/OV2640 Manufacturer identifier */
  OV2640_ReadID(&OV2640_Camera_ID);
  if(OV2640_Camera_ID.PIDH  != 0x26)
  {
    printf("camera init error\n");
    
    while(1)
    {     
       GUI_Delay(10);
    }
  }

  OV2640_QVGAConfig(); 
  OV2640_Init();   
  DCMI_Cmd(ENABLE); 
  DCMI_CaptureCmd(ENABLE); 
  OSSchedLock(&err);
  while(1)
  {     
    Key_RefreshState(&Key1);
    if(Key_AccessTimes(&Key1,KEY_ACCESS_READ)!=0)
    {
      LED2_TOGGLE;
      OV2640_Stop();
      OSSchedUnlock(&err);
      OSSemPost ((OS_SEM  *)&SEM_SHOT,
                 (OS_OPT   )OS_OPT_POST_ALL,
                 (OS_ERR  *)&err);
      Key_AccessTimes(&Key1,KEY_ACCESS_WRITE_CLEAR);
    }
    if(shot_flag==1)
    {
      shot_flag=0;
      return;
    }
  }
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
