/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/
// USER START (Optionally insert additional includes)
#include "includes.h"
#include "app.h"
#include "DIALOG.h"
#include "./Bsp/sim900a/bsp_sim900a.h"
#include "string.h"
// USER END

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
// USER START (Optionally insert additional defines)
/*--------------------  (使用U2C.exe小工具生成)  ------------------------------------*/
#define UTF8_MESSAGEDLG        "\xe7\x9f\xad\xe4\xbf\xa1"//短信
#define UTF8_STATE             "\xe7\x8a\xb6\xe6\x80\x81"//状态
#define UTF8_CONTACT           "\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba"//联系人
#define UTF8_CONTENT           "\xe5\x86\x85\xe5\xae\xb9"//内容
#define UTF8_SEND              "\xe5\x8f\x91\xe9\x80\x81"//发送
#define UTF8_UNREAD            "\xe6\x9c\xaa\xe8\xaf\xbb"//未读
#define UTF8_TO                "\xe5\x8f\x91"//发
#define UTF8_FROM              "\xe6\x94\xb6"//收
#define UTF8_CLEAR             "\xe6\xb8\x85\xe9\x99\xa4"//清除
/*-----------------------------------------------------------------------------------*/

#define MESSAGE_PATHDIR   "1:/System"
#define MESS_LIST_PATH 		"1:/System/messagelist.txt"
#define MESSAGE_MAX			  50

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
static uint8_t sim900a_flag=0;
static uint8_t messageNumRows=0;
static const char * _aTable_[1][3] = {0};
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreateMessage[] = {
  { FRAMEWIN_CreateIndirect,  "Message",                     0,  0,   0,   800, 480, 0, 0x0,  0 },
  { LISTVIEW_CreateIndirect,  "MessageList",  GUI_ID_LISTVIEW0,  0,   0,   380, 445, 0, 0x0,  0 },
  { EDIT_CreateIndirect,      "Name",         GUI_ID_EDIT0,      400, 40,  250, 30,  0, 0x14, 0 },
  { MULTIEDIT_CreateIndirect, "Information",  GUI_ID_MULTIEDIT0, 400, 100, 370, 340, 0, 0x0,  0 },
  { BUTTON_CreateIndirect,    "Send",         GUI_ID_BUTTON0,    680, 15,  80,  30,  0, 0x0,  0 },
  { BUTTON_CreateIndirect,    "Clear",        GUI_ID_BUTTON1,    680, 60,  80,  30,  0, 0x0,  0 },
  { TEXT_CreateIndirect,      "Contact",      GUI_ID_TEXT0,      400, 14,   100, 25,  0, 0x64, 0 },
  { TEXT_CreateIndirect,      "Content",      GUI_ID_TEXT1,      400, 74,  100, 25,  0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void LISTVIEW_AddItem(WM_HWIN hWin)
{
  if(sim900a_flag==0) return;
  messageNumRows=0;
  f_result=f_open(&f_file, MESS_LIST_PATH,FA_READ);
  while((f_result==FR_OK)&&(messageNumRows<MESSAGE_MAX))
  {
    f_result = f_lseek(&f_file,messageNumRows*330);
    if(f_result != FR_OK)break;
    com_data2null(&comdata[0],500);
    f_result = f_read(&f_file,comdata, 330, &f_num);
    if((f_result != FR_OK)||(f_num < 30))break;
    comdata[30+30]='\0';
    com_gbk2utf8((char *)&comdata[30],(char *)&comdata[500]);
    _aTable_[0][0]=(char *)&comdata[0];
		_aTable_[0][1]=(char *)&comdata[10];
		_aTable_[0][2]=(char *)&comdata[500];
		LISTVIEW_AddRow(WM_GetDialogItem(hWin, GUI_ID_LISTVIEW0), _aTable_[0]);
		messageNumRows++;
  }
  f_close (&f_file);
}

static void saveReceiveMessage(WM_HWIN hWin,char *num,char *gbkstr)
{    
  sprintf((char *)&comdata[0],UTF8_UNREAD);
  sprintf((char *)&comdata[10],"%s",num);
  sprintf((char *)&comdata[30],"%s",gbkstr);
  comdata[329]='\n';
  com_gbk2utf8((char *)&comdata[30],(char *)&comdata[500]);
  comdata[500+30]='\0';
  _aTable_[0][0]=(char *)&comdata[0];
  _aTable_[0][1]=(char *)&comdata[10];
  _aTable_[0][2]=(char *)&comdata[500];
  LISTVIEW_AddRow(WM_GetDialogItem(hWin, GUI_ID_LISTVIEW0), _aTable_[0]);
  sprintf((char *)&comdata[0],UTF8_FROM);
  f_result=f_open(&f_file,MESS_LIST_PATH,FA_WRITE);
  if(f_result==FR_NO_FILE)
  {
    f_result=f_open(&f_file,MESS_LIST_PATH,FA_CREATE_NEW|FA_WRITE);
    messageNumRows=0;
  }
  f_result = f_lseek(&f_file,messageNumRows*330); 
  f_result = f_write(&f_file, (char *)&comdata[0], 330, &f_num);
  messageNumRows++;
  f_close(&f_file); 
}	
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialogMessage(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static uint8_t selectindex=0xff;
  OS_ERR      err;
  // USER END

  switch (pMsg->MsgId) {
  case WM_DELETE:
    OS_INFO("Message delete\n");
    Flag_ICON9 = 0;    
    USART_ITConfig(GSM_USART, USART_IT_RXNE, DISABLE);	
    USART_Cmd(GSM_USART, DISABLE);
    GSM_USART_CLKCMD(GSM_USART_CLK, DISABLE);
    UserApp_Flag = 0;
    tpad_flag=0;
    WM_DeleteWindow(hkeypad);
    break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Message'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem,UTF8_MESSAGEDLG);
    FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
    //
    // Initialization of 'Name'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0);
    EDIT_SetText(hItem, "10086");
    EDIT_SetFont(hItem, GUI_FONT_24B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    EDIT_EnableBlink(hItem,250,1);
    EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,GUI_WHITE);
    EDIT_SetTextColor(hItem,EDIT_CI_ENABLED,GUI_BLACK);
    //
    // Initialization of 'Information'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0);
    MULTIEDIT_SetText(hItem, "Hello World");
    MULTIEDIT_SetFont(hItem, &XBF_XINSONGTI25);
		MULTIEDIT_EnableBlink(hItem,250,1);
		MULTIEDIT_SetAutoScrollV(hItem,1);
    //MULTIEDIT_SetAutoScrollH(hItem,1);
    MULTIEDIT_SetWrapWord(hItem);
    MULTIEDIT_SetInsertMode(hItem,1);
    //
    // Initialization of 'Send'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0);
    BUTTON_SetFont(hItem, &XBF_XINSONGTI19);
    BUTTON_SetText(hItem,UTF8_SEND);
    //
    // Initialization of 'Clear'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON1);
    BUTTON_SetFont(hItem, &XBF_XINSONGTI19);
    BUTTON_SetText(hItem,UTF8_CLEAR);
    //
    // Initialization of 'Contact'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
    TEXT_SetFont(hItem, &XBF_XINSONGTI19);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_BOTTOM);
    TEXT_SetText(hItem, UTF8_CONTACT);
    TEXT_SetTextColor(hItem,GUI_LIGHTGREEN);
    //
    // Initialization of 'Content'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT1);
    TEXT_SetFont(hItem, &XBF_XINSONGTI19);
    TEXT_SetText(hItem, UTF8_CONTENT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_BOTTOM);
    TEXT_SetTextColor(hItem,GUI_LIGHTGREEN);
    //
    // Initialization of 'MessageList'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTVIEW0);
    HEADER_SetFont(LISTVIEW_GetHeader(hItem),&XBF_XINSONGTI25);
    LISTVIEW_AddColumn(hItem, 50, UTF8_STATE, GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 160, UTF8_CONTACT, GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 170, UTF8_CONTENT, GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_SetFont(hItem, &XBF_XINSONGTI19);
    LISTVIEW_SetAutoScrollV(hItem, 1);
    LISTVIEW_SetHeaderHeight(hItem, 28);
    LISTVIEW_SetRowHeight(hItem, 24);
    LISTVIEW_SetTextAlign(hItem,0,GUI_TA_HCENTER | GUI_TA_VCENTER);
	  LISTVIEW_SetTextAlign(hItem,1,GUI_TA_HCENTER | GUI_TA_VCENTER);
	  LISTVIEW_SetTextAlign(hItem,2,GUI_TA_LEFT | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    selectindex=0xff;
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case GUI_ID_LISTVIEW0: // Notifications sent by 'MessageList'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        selectindex=LISTVIEW_GetSel(WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTVIEW0));
        WM_HasFocus(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0));
        f_result=f_open(&f_file, MESS_LIST_PATH,FA_READ);
        if(f_result==FR_OK)
        {
          f_result = f_lseek(&f_file,selectindex*330);
          com_data2null(&comdata[0],500);
          f_result = f_read(&f_file,comdata, 330, &f_num);
          if((f_result != FR_OK)||(f_num < 30))
          {
            EDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0), "");
            MULTIEDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0), "");
            f_close (&f_file);
            break;
          }
          EDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0), (char *)&comdata[10]);
          com_gbk2utf8((char *)&comdata[30],(char *)&comdata[500]);
          MULTIEDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0), (char *)&comdata[500]);
        }
        f_close (&f_file);
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case GUI_ID_EDIT0: // Notifications sent by 'Name'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        KeyPad_Interface(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0),0);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case GUI_ID_MULTIEDIT0: // Notifications sent by 'Information'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        KeyPad_Interface(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0),1);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case GUI_ID_BUTTON0: // Notifications sent by 'Send'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        OSSchedLock(&err);
        com_data2null(&comdata[0],1000);
        EDIT_GetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0), (char *)&comdata[10],20);
        hItem=WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0);
        MULTIEDIT_GetText(hItem,(char *)&comdata[500],MULTIEDIT_GetTextSize(hItem));
        if(sim900a_flag==1)
        {
          sim900a_sms_utf8((char *)&comdata[10],(char *)&comdata[500],strlen((char *)&comdata[10]),MULTIEDIT_GetTextSize(hItem));
        }
        sprintf((char *)&comdata[0],UTF8_TO); 
        com_utf82gbk((char *)&comdata[500],(char *)&comdata[30]);
        comdata[329]='\n';
        comdata[500+30]='\0';
        _aTable_[0][0]=(char *)&comdata[0];
        _aTable_[0][1]=(char *)&comdata[10];
        _aTable_[0][2]=(char *)&comdata[500];
        LISTVIEW_AddRow(WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTVIEW0), _aTable_[0]);
        EDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0), "");
        MULTIEDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0), "");
        f_result=f_open(&f_file,MESS_LIST_PATH,FA_WRITE);
        if(f_result==FR_NO_FILE)
        {
          f_result=f_open(&f_file,MESS_LIST_PATH,FA_CREATE_NEW|FA_WRITE);
          messageNumRows=0;
        }
        if(selectindex==0xff)
        {
          f_result = f_lseek(&f_file,messageNumRows*330); 
          messageNumRows++;          
        }
        else
        {
          f_result = f_lseek(&f_file,selectindex*330);          
        }
        selectindex=0xff;
        f_result = f_write(&f_file, (char *)&comdata[0], 330, &f_num);
        OSSchedUnlock(&err);
        f_close(&f_file); 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case GUI_ID_BUTTON1: // Notifications sent by 'Clear'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:       
        EDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0), "");
        MULTIEDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0), "");        
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMessage
*/
void FUN_ICON9Clicked(void)
{
  WM_HWIN hWin;
  OS_ERR  err;
  uint8_t newmessadd=0,IsRead=0;
  uint8_t timecount=0;
  char messagename[20];
  OS_INFO("MessageDLG create\n");  
  com_createdir(MESSAGE_PATHDIR);
  hWin = GUI_CreateDialogBox(_aDialogCreateMessage, GUI_COUNTOF(_aDialogCreateMessage), _cbDialogMessage, HDTWIN, 0, 0);
  GUI_Delay(100);
  /* 初始化并检测模块 */
	if(sim900a_init()!= SIM900A_TRUE)
	{
    sim900a_flag=0;
    ErrorDialog(hWin,"GSM Error","SIM900A Module cannot work!");
    while(1)
    {
      if(tpad_flag)WM_DeleteWindow(hWin);
       if(!Flag_ICON9)return;
       GUI_Delay(10);
    }
	}
  sim900a_flag=1;
  LISTVIEW_AddItem(hWin);   
  sim900a_tx_printf("AT+CNMI=2,1\r");
  SIM900A_DELAY(100);  
  sim900a_tx_printf("AT+CMGF=1\r");           //文本模式
  SIM900A_DELAY(100);
  SIM900A_CLEAN_RX();//清除接收缓存
  while(Flag_ICON9)
	{
    if(timecount>100)
		{
			newmessadd=IsReceiveMS();      
			if(newmessadd)
			{	
				SIM900A_DELAY(500); 
        sim900a_tx_printf("AT+CSCS=\"UCS2\"\r");     //"GSM"字符集        
        SIM900A_DELAY(500);        
				BEEP_ON;
        OSSchedLock(&err);
        SIM900A_CLEAN_RX();//清除接收缓存
        com_data2null(&comdata[1000],2000);
        SIM900A_DELAY(100);
				IsRead=readmessage(newmessadd,(char *)&comdata[1000],(char *)&comdata[1200]); 
				printf("IsRead->(%d)\n",IsRead);
        if(IsRead)
				{
					hexuni2gbk((char *)&comdata[1000],messagename);	
					hexuni2gbk((char *)&comdata[1200],(char *)&comdata[2000]);	
          printf("name->(%s) mes->(%s)\n",messagename,(char *)&comdata[2000]);          
					saveReceiveMessage(hWin,messagename,(char *)&comdata[2000]);					
				}     
        OSSchedUnlock(&err);
        sim900a_tx_printf("AT+CMGD=%d\r",newmessadd);
        SIM900A_DELAY(100);
			}      
			SIM900A_CLEAN_RX();
			BEEP_OFF;
			timecount=0;      
		}
		timecount++;
    if(tpad_flag)WM_DeleteWindow(hWin);
		GUI_Delay(10);
  }
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
